POST http://localhost:3000/users
Content-Type: application/json

{
    "userId":"1",
    "isAdmin":"false",
    "isStaff":"false",
    "firstName":"john",
    "lastName":"smith",
    "phoneNumber":"2125551212",
    "cellNumber":"2126661212",
    "email":"1@me.com",
    "unit":"13A",
    "department":"",
    "userStatus":"active"
}